# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-20 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import dvhb_hybrid.email_templates.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='update at')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='name')),
                ('description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'message template',
                'verbose_name_plural': 'message templates',
            },
        ),
        migrations.CreateModel(
            name='TemplateTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='update at')),
                ('lang_code', models.CharField(db_index=True, max_length=2, validators=[dvhb_hybrid.email_templates.models.validate_lang_code], verbose_name='language code')),
                ('message_subject', models.CharField(max_length=1024, verbose_name='subject')),
                ('message_body', models.CharField(max_length=4096, verbose_name='body')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email_templates.Template')),
            ],
            options={
                'verbose_name': 'message template translation',
                'verbose_name_plural': 'message template translations',
            },
        ),
        migrations.AlterUniqueTogether(
            name='templatetranslation',
            unique_together=set([('template', 'lang_code')]),
        ),
    ]
