# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-25 13:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActionLogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('ip_address', models.CharField(max_length=255, null=True, verbose_name='user IP')),
                ('message', models.TextField(verbose_name='log message')),
                ('type', models.CharField(choices=[('reg', 'User registration'), ('auth', 'User authentification'), ('crud', 'CRUD'), ('email', 'Email')], max_length=20, verbose_name='action type')),
                ('subtype', models.CharField(choices=[('create', 'Created'), ('update', 'Changed'), ('delete', 'Deleted'), ('login', 'Login'), ('logout', 'Logout'), ('change_password', 'Change password')], max_length=20, verbose_name='action subtype')),
                ('payload', models.JSONField(null=True, verbose_name='additional data')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'user action log record',
                'ordering': ('-created_at',),
            },
        ),
    ]
