# Generated by Django 2.0.4 on 2018-04-05 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('user_action_log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractionlogentry',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='useractionlogentry',
            name='object_id',
            field=models.TextField(blank=True, null=True, verbose_name='object id'),
        ),
        migrations.AddField(
            model_name='useractionlogentry',
            name='object_repr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='object repr'),
        ),
    ]
