# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-24 10:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_action_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractionlogentry',
            name='subtype',
            field=models.CharField(choices=[('create', 'Created'), ('update', 'Changed'), ('delete', 'Deleted'), ('login', 'Login'), ('logout', 'Logout'), ('change_password', 'Change password')], max_length=20, verbose_name='action subtype'),
        ),
    ]
